name: Elixir CI

on:
  push:
    branches: [ "main", "code-implement" ]
  pull_request:
    branches: [ "main", "code-implement" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15'
          otp-version: '26.0'
      - name: Install dependencies
        run: mix deps.get
      - name: Build escript
        run: mix escript.build
      - name: Upload escript artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./ledger_cli

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15'
          otp-version: '26.0'
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15'
          otp-version: '26.0'
      - name: Install dependencies
        run: mix deps.get
      - name: Run coverage
        run: mix test --cover
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: cover/
